const defaultFilters = [
	"*://*.doubleclick.net/*",
	"*://*.googlesyndication.com/*",
	"*://partner.googleadservices.com/*",
	"*://*.google-analytics.com/*",
	"*://creative.ak.fbcdn.net/*",
	"*://*.ads.yahoo.com/*",
	"*://*.adnxs.com/*",
	"*://*.adsrvr.org/*",
	"*://*.rubiconproject.com/*",
	"*://*.adform.net/*",
	"*://*.outbrain.com/*",
	"*://*.taboola.com/*",
	"*://*.moatads.com/*",
	"*://*.criteo.com/*",
	"*://*.media.net/*",
	"*://*.bidswitch.net/*",
	"*://*.pubmatic.com/*",
	"*://*.openx.net/*",
	"*://*.adroll.com/*",
	"*://*.smartadserver.com/*",
	"*://*.advertising.com/*",
	"*://*.revcontent.com/*",
	"*://*.connexity.net/*",
	"*://*.contextweb.com/*",
	"*://*.trafficjunky.net/*",
	"*://*.mgid.com/*",
	"*://*.adcolony.com/*",
	"*://*.inmobi.com/*",
	"*://*.yandex.ru/*",
	"*://*.adblade.com/*",
	"*://*.zedo.com/*",
	"*://*.scorecardresearch.com/*",
	"*://*.quantserve.com/*",
	"*://*.exponential.com/*",
	"*://*.adbrite.com/*",
	"*://*.vserv.mobi/*",
	"*://*.tyroo.com/*",
	"*://*.affle.com/*",
	"*://*.smaato.com/*",
	"*://*.mobfox.com/*",
	"*://*.madvertise.de/*",
	"*://*.dream11.com/*",
	"*://*.winzo.com/*",
	"*://*.my11circle.com/*",
	"*://*.1xbet.com/*",
	"*://*.pari-matchin.com/*",
	"*://*.betway.com/*",
	"*://*.jeetwin.com/*",
	"*://*.10cric.com/*"
];

chrome.webRequest.onBeforeRequest.addListener(
	function(details) { return { cancel: true } },
	{ urls: defaultFilters },
	["blocking"]
);

